version: '3.5'


services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  db:
    container_name: ordersDbDeploy
    image: postgres
    ports:
      - '5001:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  pgdata:

